version: '2'
services:
  gpdb5a:
        image: "kochanpivotal/gpdb5-pxf"
        command: bin/bash
        hostname: "gpdb5a"
        container_name: gpdb5a
        environment:
          - START_GPDB=yes
          - START_PXF=yes
          - COMPOSE_HTTP_TIMEOUT=120 # default is 60
        ports:
         - "5432:5432"
         - "5005:5005"
         - "5010:5010"
         - "9022:22"
         - "40000:40000"
         - "40001:40001"
         - "40002:40002"
        expose:
         - "5432"
        volumes:
         - ..:/code

        tty: true
        networks:
          mynetwork:
            aliases:
              - gpdb5a
              - gpdb5a.localdomain.com
  gpdb5b:
        image: "kochanpivotal/gpdb5-pxf"
        command: bin/bash
        hostname: "gpdb5b"
        container_name: gpdb5b
        environment:
          - START_GPDB=yes
          - START_PXF=yes
          - COMPOSE_HTTP_TIMEOUT=120 # default is 60
        ports:
         - "6432:5432"
         - "6005:5005"
         - "6010:5010"
         - "19022:22"
         - "50000:40000"
         - "50001:40001"
         - "50002:40002"
        expose:
         - "6432"
        volumes:
         - ..:/code
        tty: true
        networks:
          mynetwork:
            aliases:
              - gpdb5b
              - gpdb5b.localdomain.com
networks:
    mynetwork:
      driver: bridge
