version: '2'
services:
  gemfirelocator:
    image: apachegeode/geode
    hostname: locator
    mem_limit: 512m
    expose:
     - "10334"
     - "1099"
     - "7575"
     - "7070:7070"
    ports:
     - "1099:1099"
     - "10334:10334"
     - "7575:7575"
     - "7070:7070"
    volumes:
     - ./gemfiredata/scripts/:/scripts/
     - ..:/code
    command: /scripts/gfshWrapper.sh gfsh start locator --name=locator --mcast-port=0
    tty: true
    networks:
      mynetwork:
        aliases:
          - locator
          - locator.localdomain.com

  gemfireserver:
    image: apachegeode/geode
    mem_limit: 2g
    hostname: "gemfireserver"
    expose:
     - "8080"
     - "40404"
     - "1099"
    ports:
       - "8080"
       - "40404"
       - "1099"
    volumes:
     - ./gemfiredata/scripts/:/scripts/
     - ..:/code
    command: /scripts/startServer.sh --server-port=40404 --max-heap=1G
    tty: true
    networks:
      mynetwork:
        aliases:
          - gemfireserver
          - gemfireserver.localdomain.com
  gpdb5:
        #build:
        #  context: .
        #  dockerfile: ./gpdb/Dockerfile
        image: "kochanpivotal/gpdb5-pxf"
        command: bin/bash
        hostname: "gpdbsne"
        container_name: gpdbsne
        ports:
         - "5432:5432"
         - "5005:5005"
         - "5010:5010"
         - "9022:22"
         - "40000:40000"
         - "40001:40001"
         - "40002:40002"
        expose:
         - "5432"
        volumes:
         - ..:/code
        tty: true
        networks:
          mynetwork:
            aliases:
              - gpdbsne
              - gpdbsne.localdomain.com
networks:
    mynetwork:
      driver: bridge
