source 'https://rubygems.org'

gem "github-pages", "163", group: :jekyll_plugins
gem "nokogiri", ">= 1.12.5"
gem "kramdown", ">= 2.3.0"
gem "addressable", ">= 2.8.0"

# enable tzinfo-data for local build
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'jekyll-paginate'
