version: '2'
services:
# POSTGRESQL_DB: A database that is automatically created if it doesn't exist. Default: docker
# POSTGRESQL_USER: A user to create that has access to the database specified by POSTGRESQL_DB. Default: docker
# POSTGRESQL_PASS: The password for POSTGRESQL_USER. Default: docker
  postgres:
    image: dequis/postgresql-8.3
    hostname: "postgresql"
    container_name: postgresql
    environment:
        POSTGRESQL_DB: docker
        POSTGRESQL_USER: dbuser
        POSTGRESQL_PASS: dbuserpass
    ports:
      - "6432:5432"

    volumes:
       - ..:/code
    tty: true
    privileged: true
    links:
         - gpdb5:gpdbsne
    networks:
      mynetwork:
        aliases:
          - postgres
          - postgres.localdomain.com

  gpdb5:
        #build:
        #  context: .
        #  dockerfile: ./gpdb/Dockerfile
        image: "kochanpivotal/gpdb5-pxf"
        command: bin/bash
        hostname: "gpdbsne"
        container_name: gpdbsne
        ports:
         - "5432:5432"
         - "5005:5005"
         - "5010:5010"
         - "9022:22"
         - "40000:40000"
         - "40001:40001"
         - "40002:40002"
        expose:
         - "5432"
        volumes:
         - ..:/code

        tty: true
        networks:
          mynetwork:
            aliases:
              - gpdbsne
              - gpdbsne.localdomain.com
networks:
    mynetwork:
      driver: bridge
